yatube/about/urls.py
from about import views
from django.urls import path

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
    )

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название сообщества', max_length=200)
    slug = models.SlugField('Ссылка сообщества', unique=True)
    description = models.TextField('Описание сообщества', max_length=200)

    class Meta:
        verbose_name = 'сообщество'
        verbose_name_plural = 'сообщества'

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name='Автор',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        default_related_name = 'posts'
        verbose_name = 'запись'
        verbose_name_plural = 'записи'

    def __str__(self) -> str:
        return self.text[:settings.CUT_TEXT]


class Comment(models.Model):
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    post = models.ForeignKey(
        Post,
        blank=True, null=True,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Запись',
    )

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

    def __str__(self):
        return self.text[:settings.CUT_TEXT]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        verbose_name = 'подписчик'
        verbose_name_plural = 'подписчики'
        constraints = [
            UniqueConstraint(
                fields=['user', 'author'], name='unique_author_user',
            ),
        ]

    def __str__(self):
        return f'{self.user.username}, {self.following.username}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            "text": "Текст поста",
            "group": "Группа",
            "image": "Изображение",

        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Follow, Group, Post
from .utils import paginator

User = get_user_model()


def index(request):
    posts = Post.objects.select_related('author', 'group').all()
    return render(request, 'posts/index.html',
                  {'page_obj': paginator(posts, request)})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': paginator(posts, request),
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group')
    context = {
        'author': author,
        'page_obj': paginator(posts, request),
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    request.FILES or None)

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:
        return redirect('posts:post_detail',
                        post_id=post.id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        post.save()
        return redirect('posts:post_detail', pk)
    return render(request, 'posts/create_post.html',
                  {'is_edit': True, 'form': form})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    context = {
        'page_obj': paginator(posts, request),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(author=author, user=request.user)
    return redirect('posts:profile', author.username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=user, author=author).first()
    if follow:
        follow.delete()
    return redirect('posts:profile', author.username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
    {% if is_edit %}
        <title>Редактирование поста</title>
    {% else %}
        <title>Создание поста</title>
    {% endif %}
{% endblock title %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            {$ include "posts/includes/form/errors.html" %}
            <div class="card ">
                <div class="card-header">
                    {% if is_edit %}
                        Редактировать пост
                    {% else %}
                        Добавить пост
                    {% endif %}
                </div>
                <div class="card-body ">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {$ include "includes/form/field.html" $}
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                                {% if is_edit %}
                                    Добавить
                                {% else %}
                                    Сохранить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Мои подписки{% endblock %}
{% block content %}
    <div class="container py-4">
        <div class="mb-4">
            <div class="mb-4">
                <h1 class="display-5">Последние обновления моих подписок</h1>
            </div>
            {% include 'posts/includes/switcher.html' %}
            {% for post in page_obj %}
                {% include 'posts/includes/post.html' %}
            {% endfor %}
            {% include 'posts/includes/paginator.html' %}
        </div>
    {% endblock content %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
    {{ group.title }}
{% endblock title %}
{% block content %}
    <div class="container">
        <h1>{{ group.title }}</h1>
        <p>{{ group.description }}</p>
        {% for post in posts %}
            {% include "posts/includes/post.html" %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
    </div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Последние обновления на сайте
{% endblock title %}
{% block content %}
    {% include 'posts/includes/switcher.html' %}
    {% load cache %}
    {% cache 20 index_page with page_obj %}
    <div class="container">
        <h1>Последние обновления на сайте</h1>
        {% for post in page_obj %}
            {% include 'posts/includes/post.html' %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endcache %}
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}
    <title>{{ post.text|truncatechars_html:30 }}</title>
{% endblock title %}
{% block content %}
    {% load thumbnail %}
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            {% if posts.group %}
                <li class="list-group-item">
                    Группа: {{ post.group.title }}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                {% endif %}
            </li>
            <li class="list-group-item">Автор: {{ post.author.get_full_name }}</li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора: <span>{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
        </ul>
    </aside>
    <article class="col-12 col-md-9">
        <p>{{ post.text|linebreaksbr }}</p>
    </article>
</div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Все записи пользователя {{ author }}{% endblock %}
{% block content %}
    <h3>Всего постов: {{ author.posts.count }}</h3>
    {% if request.user != author %}
        {% if following %}
            <a class="btn btn-lg btn-light"
               href="{% url 'posts:profile_unfollow' author.username %}"
               role="button">Отписаться</a>
        {% else %}
            <a class="btn btn-lg btn-primary"
               href="{% url 'posts:profile_follow' author.username %}"
               role="button">Подписаться</a>
        {% endif %}
    {% endif %}
    {% for post in page_obj %}
        {% include 'posts/includes/post.html' %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}